---

#=================== Ubuntu Servers ======================
- hosts: Ubuntu_servers
  gather_facts: false
  become: true
  tasks:

  - name: update the ubuntu repos and install packages
    tags: ubuntu
    package:
        name:
# "*" ==> Upgrades all the packages
          #  - "*"
           - htop
           - curl
           - stress-ng
        state: latest
        # state: absent       # To remove the packages from the servers
        update_cache: yes

  - name: Remove dependencies which are no longer required
    tags: ubuntu
    package:
        autoremove: yes
        purge: yes            # Use purge with autoremove


#==================== Linux Lite =======================
- hosts: Linux_lite_server
  vars:
       ansible_python_interpreter: /usr/bin/python3
       ansible_connection: ssh
       scp_if_ssh: true
  gather_facts: false
  become: true
  tasks:

  - name: update the linux lite repos and install packages
    tags: lite
    package:
        name:
# "*" ==> Upgrades all the packages
          #  - "*"
           - htop
           - stress-ng
           - traceroute
        state: latest
        update_cache: yes

  - name: Remove dependencies which are no longer required
    tags: lite
    package:
        autoremove: yes
        purge: yes            # Use purge with autoremove


#=================== POP server ========================
- hosts: Pop_server
  vars:
       ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  become: true
  become_method: su
  become_user: root
  tasks:

  - name: update the pop repos and install packages
    tags: pop
    package:
        name:
          #  - "*"
           - htop
           - stress-ng
        state: latest
        update_cache: yes

  - name: Remove dependencies which are no longer required
    tags: pop
    package:
        autoremove: yes
        purge: yes            # Use purge with autoremove


#=================== CentOS Server ========================
- hosts: CentOS_servers
  vars:
       ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  become: true
  become_method: su
  become_user: root
  tasks:

  - name: update the centos repos and install packages
    tags: centos
    package:
        name:
          #  - "*"
           - epel-release
           - htop
           - httpd
           - stress-ng
        state: latest
        update_cache: yes

  - name: Remove dependencies which are no longer required
    tags: centos
    package:
        autoremove: yes
        #purge: yes            # Use purge with autoremove


